kafka:
  topic_name: "url_queue"
  bootstrap_servers: "localhost:9092"
  group_id: "scraper_group"
  auto_offset_reset: "earliest"
  enable_auto_commit: true
  max_poll_interval_ms: 300000
  session_timeout_ms: 45000
  socket_timeout_ms: 60000

scraper:
  headless: True
  slow_mo: 0  # in milliseconds
  metadata_file: "scraped_data/metadata.json"

database:
  dbname: "web_crawler_db"
  user: "db_user"
  password: "password"
  host: "localhost"
  port: 5432

# Url data
tranco:
  list_date: "2024-01-01"
  top_n: 10000
  cache_dir: "url_data"
