kafka:
  topic_name: "url_queue"
  bootstrap_servers: "localhost:9092"
  group_id: "scraper_group"

scraper:
  urls:
    - "https://google.com"
    - "https://amazon.com"
    - "https://example.com"
    - "https://dell.com"
  headless: true
  slow_mo: 0  # in milliseconds
  metadata_file: "scraped_data/metadata.json"

database:
  dbname: "your_db_name"
  user: "your_username"
  password: "your_password"
  host: "localhost"
  port: 5432