kafka:
  topic_name: "url_queue"
  bootstrap_servers: "localhost:9092"
  group_id: "scraper_group"

scraper:
  headless: True
  slow_mo: 0  # in milliseconds
  metadata_file: "scraped_data/metadata.json"

database:
  dbname: "web_crawler_db"
  user: "db_user"
  password: "password"
  host: "localhost"
  port: 5432