kafka:
  topic_name: "url_queue"
  bootstrap_servers: "localhost:9092"
  group_id: "scraper_group"

scraper:
  urls:
    - "https://google.com"
    - "https://amazon.com"
    - "https://example.com"
    - "https://dell.com"
  headless: true
  slow_mo: 0  # in milliseconds
  metadata_file: "scraped_data/metadata.json"

# docker:
#   zookeeper:
#     container_name: "zookeeper"
#     image: "confluentinc/cp-zookeeper:7.5.0"
#     environment:
#       ZOOKEEPER_CLIENT_PORT: 2181
#       ZOOKEEPER_TICK_TIME: 2000
#     ports:
#       - "2181:2181"

#   kafka:
#     container_name: "kafka"
#     image: "confluentinc/cp-kafka:7.5.0"
#     depends_on:
#       - "zookeeper"
#     ports:
#       - "9092:9092"
#     environment:
#       KAFKA_BROKER_ID: 1
#       KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
#       KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
